name: straglr
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8.13
  - pysam>=0.14.0
  - pybedtools>=0.9.0
  - numpy>=1.22.3
  - pathos>=0.2.3
  - scikit-learn>=1.1
  - scipy>=1.8.0
  - trf=4.09.1
  - blast
  - pip
  - pip:
      - git+https://github.com/bcgsc/straglr.git@v1.5.5